import { NextIntlClientProvider, useLocale } from 'next-intl';

import OrbitPrimary from '@/components/ui/orbits/orbit-primary';
import OrbitSecondary from '@/components/ui/orbits/orbit-secondary';
import OrbitVignette from '@/components/ui/orbits/orbit-vignette';

import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const locale = useLocale();

  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body className='h-screen'>
        <OrbitPrimary />
        <OrbitSecondary />
        <OrbitVignette />
        <NextIntlClientProvider>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
